import React, { useState, useEffect } from 'react';
import axios from 'axios';
import './App.css';

function App() {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [backtestStatus, setBacktestStatus] = useState("Run Backtest");

    useEffect(() => {
        fetchPrediction();
    }, []);

    const fetchPrediction = async () => {
        try {
            const res = await axios.get('http://localhost:8000/prediction');
            setData(res.data);
            setLoading(false);
        } catch (err) {
            console.error(err);
            setLoading(false);
        }
    };

    const runBacktest = async () => {
        setBacktestStatus("Running...");
        try {
            await axios.get('http://localhost:8000/backtest');
            setBacktestStatus("Done! Refreshing...");
            setTimeout(() => window.location.reload(), 1000);
        } catch (err) {
            setBacktestStatus("Error");
        }
    };

    return (
        <div className="App">
            <header className="App-header">
                <h1>🚀 AI Trading Agent</h1>
                <p>Student MVP - LSTM Model</p>
            </header>

            <div className="container">
                {/* Prediction Card */}
                <div className="card prediction-card">
                    <h2>Market Forecast (AAPL)</h2>
                    {loading ? (
                        <p>Loading Model...</p>
                    ) : data ? (
                        <div className={`prediction ${data.prediction}`}>
                            <div className="main-pred">
                                {data.prediction === "UP" ? "📈 BULLISH" : data.prediction === "DOWN" ? "📉 BEARISH" : "➡ NEUTRAL"}
                            </div>
                            <div className="confidence">
                                Confidence: <strong>{data.confidence}%</strong>
                            </div>
                            <div className="details">
                                <p>Date: {data.date}</p>
                                <p>Close: ${data.features.Close.toFixed(2)}</p>
                                <p>RSI: {data.features.RSI.toFixed(1)}</p>
                            </div>
                        </div>
                    ) : (
                        <p className="error">Model Disconnected</p>
                    )}
                </div>

                {/* Backtest Section */}
                <div className="card backtest-card">
                    <div className="card-header">
                        <h2>Performance (2024 Test)</h2>
                        <button onClick={runBacktest} disabled={backtestStatus === "Running..."}>
                            {backtestStatus}
                        </button>
                    </div>
                    <div className="chart-container">
                        {/* Display the generated image from backtest.py */}
                        <img
                            src="/backtest_chart.png"
                            alt="Run backtest to see chart"
                            onError={(e) => e.target.style.display = 'none'}
                        />
                        <p className="note">*Chart generated by Python backend</p>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default App;
